version: '3.8'

services:
  go53:
    build: .
    container_name: go53
    ports:
      - "1053:53/udp"
      - "8053:8053"
    volumes:
      - ./:/app
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8053"]
      interval: 30s
      timeout: 5s
      retries: 3

