options {
	directory "/tmp";
	listen-on port 53 { any; };
	listen-on-v6 { none; };
	recursion no;
	dnssec-validation no;
	notify yes;
};

key "catalog-key." {
	algorithm hmac-sha256;
	secret "YWJjMTIz";
};

zone "catalog-member-a.test." {
	type primary;
	file "/zones/db.catalog-member-a.test";
	allow-transfer { key "catalog-key."; };
	also-notify { 10.53.0.10 port 2053; };
};
